name: "Manage labels for pull requests"

on:
  pull_request:
    types:
      - labeled
      - opened
      - review_requested
  pull_request_review:
    types:
      - submitted

jobs:
  label_manager:
    runs-on: ubuntu-latest
    steps:
      - uses: fundamerica/github_actions@v1.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          approval-count: 2